import { Mail, MessageCircle, Send } from 'lucide-react'
import { useState } from 'react'
import { toast } from 'react-toastify'

export default function Contact() {
  const [loading, setLoading] = useState(false)
  const [form, setForm] = useState({ name: '', email: '', message: '' })
  const submit = async (event) => { event.preventDefault(); setLoading(true); try { const response = await fetch('/api/contact', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(form) }); const data = await response.json(); if (!response.ok) throw new Error(data.error); toast.success('Message sent. We will reply soon.'); setForm({ name: '', email: '', message: '' }) } catch { toast.error('Message could not be sent. Please email us directly.') } finally { setLoading(false) } }
  return <section className="container-shell py-16 sm:py-24"><div className="mx-auto max-w-2xl text-center"><span className="eyebrow">Support</span><h1 className="mt-5 font-display text-5xl font-bold uppercase text-white sm:text-7xl">Let’s <span className="text-lime">talk</span></h1><p className="mt-4 text-sm text-slate-500">Questions about a plan or an existing order? We’re here to help.</p></div><div className="mx-auto mt-12 grid max-w-5xl gap-6 md:grid-cols-[.8fr_1.2fr]"><div className="space-y-4"><ContactCard icon={Mail} title="Email support" value={import.meta.env.VITE_SUPPORT_EMAIL || 'support@sensistore.in'} /><ContactCard icon={MessageCircle} title="Community" value="Discord & Instagram links below" /><div className="rounded-xl border border-lime/15 bg-lime/[0.05] p-5 text-xs leading-5 text-slate-400">Typical response time: within 24 hours. For order help, include your Order ID.</div></div><form onSubmit={submit} className="glass-panel rounded-2xl p-6 sm:p-8"><div className="grid gap-5 sm:grid-cols-2"><Field label="Name" value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} /><Field label="Email" type="email" value={form.email} onChange={(e) => setForm({ ...form, email: e.target.value })} /></div><div className="mt-5"><label className="label">Message</label><textarea required minLength="10" maxLength="2000" rows="6" className="input-field resize-none" value={form.message} onChange={(e) => setForm({ ...form, message: e.target.value })} placeholder="How can we help?" /></div><button disabled={loading} className="btn-primary mt-5 w-full">{loading ? 'Sending…' : <>Send message <Send size={15} /></>}</button></form></div></section>
}
function ContactCard({ icon: Icon, title, value }) { return <div className="glass-panel rounded-xl p-5"><Icon className="text-lime" size={20} /><p className="mt-4 text-xs font-bold uppercase tracking-wider text-white">{title}</p><p className="mt-1 break-all text-xs text-slate-500">{value}</p></div> }
function Field({ label, ...props }) { return <div><label className="label">{label}</label><input required minLength="2" maxLength="120" className="input-field" {...props} /></div> }
